Numpy is the genral purpose array processing package.
It provide high performance multidirectional array object. and tools to woring on this array. 

In [1]:
import numpy as np

In [18]:
lst = [1,2,3,4,5,6]
array = np.array(lst)

In [19]:
type(arr)

numpy.ndarray

In [21]:
print(array)

[1 2 3 4 5 6]


In [22]:
array.shape

(6,)

In [7]:
lst1 = [1,2,3,4,5]
lst2 = [2,3,4,5,6]
lst3 = [9,7,6,8,9]

arr = np.array([lst1, lst2, lst3])

In [8]:
arr

array([[1, 2, 3, 4, 5],
       [2, 3, 4, 5, 6],
       [9, 7, 6, 8, 9]])

In [10]:
arr.shape

(3, 5)

In [11]:
arr.reshape(5,3)

array([[1, 2, 3],
       [4, 5, 2],
       [3, 4, 5],
       [6, 9, 7],
       [6, 8, 9]])

In [13]:
arr.reshape(15,1)

array([[1],
       [2],
       [3],
       [4],
       [5],
       [2],
       [3],
       [4],
       [5],
       [6],
       [9],
       [7],
       [6],
       [8],
       [9]])

In [14]:
arr.reshape(1,15)

array([[1, 2, 3, 4, 5, 2, 3, 4, 5, 6, 9, 7, 6, 8, 9]])

In [15]:
arr.shape

(3, 5)

In [16]:
arr

array([[1, 2, 3, 4, 5],
       [2, 3, 4, 5, 6],
       [9, 7, 6, 8, 9]])

In [24]:
array[3]

4

In [25]:
arr
arr[1:,3:]

array([[5, 6],
       [8, 9]])

In [26]:
arr[:,:]

array([[1, 2, 3, 4, 5],
       [2, 3, 4, 5, 6],
       [9, 7, 6, 8, 9]])